### PR TITLE
Addition of swagger definition, liveness probe -> db check, graceful shutdown

### PR DESCRIPTION
**Pull request by deewhyweb**

### CODE REVIEW

**Comment by lholmquist** [comment]
I think i like everything here except the addition of swagger.  Adding in swagger quickly changes this example from a basic CRUD example using express to a swagger example.  I think that was the main argument from the other runtimes, that if we are going to include swagger, it would be its own example app. 

I think the swagger stuff takes away a little but of the simplicity that we are trying to show.

I wouldn't be opposed to just a straight up swagger/open-api node example by itself

@lance you have thoughts on this?

**Comment by lance** [comment]
@lholmquist I'm a bit ambivalent. I see your point about the added complexity. But I think @deewhyweb's goal of building an app that demonstrates "cloud-native" structure/features is important. I think we want to demonstrate, in general, what a cloud-native app should look like and this seems to fit that bill. If we did a straight-up swagger example, we'd still want a CRUD API to demonstrate. And having persistent storage for that example would be good. And of course liveness/readiness probes. So then we end right back at this example - but now we've duplicated it.

**Comment by lholmquist** [comment]
One of the original ideas around these starter applications, was to only show one piece of functionality per booster.   Adding this stuff would sort of break that principle.

I do like all these additions, so i would suggest that we talk about creating a "Cloud Native" starter application, instead of adding them here.  If we wanted to have this as part of the launcher catalog, we would probably need to bring this up with the other runtimes since these concepts are not node.js specific

**Comment by deewhyweb** [comment]
@lholmquist @lance 
I'm working on a Cloud Native node.js application currently, I'll send you a link to the repo once this is ready.

**Comment by lholmquist** [comment]
going to close this, since we are talking about creating a specific cloud native starter

**Pull request closed without merging**
