### PR TITLE
chore: Extra codes removed

### PR DESCRIPTION
**Pull request by pnaik1**

### CODE REVIEW

**Review by helio-frota — APPROVED** [review]
awesome

**Comment by yselkowitz** [comment]
These templates were used in OpenShift samples and testsuite, and their sudden no-notice removal is causing failures in https://github.com/openshift/cluster-samples-operator/pull/471.  Please revert this and update them to `nodejs:16-el8`.  If you wish to no longer maintain them, then their removal needs to be coordinated with the OpenShift team.

cc @fbm3307 @lholmquist

**Comment by helio-frota** [comment]
@yselkowitz thank you for the heads up.

I asked for that removal because it was related to the launcher.
But it seems to be used in other place as well.

Yeah let's revert that and keep the things working then.

**Comment by mhdawson** [comment]
@helio-frota can you also add the links to the sample in our tracking list for the openshift-starters repo. That will help us track what depends on the sample.

**Comment by yselkowitz** [comment]
> I asked for that removal because it was related to the launcher. But it seems to be used in other place as well.

FWIW we don't need the files in `.openshiftio`, just the ones in `.openshift`.

**Comment by helio-frota** [comment]
@yselkowitz thank you

**Pull request merged**
